name: Update Version JSON

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update version.json
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          jq --arg v "$VERSION" --arg u "${{ github.event.release.assets[0].browser_download_url }}" \
            '.version = $v | .url = $u' version.json > tmp.json && mv tmp.json version.json

      - uses: stefanzweifel/git-auto-commit-action@v5
